namespace BetterFG.Core
{
    public static partial class BetterFGInfo
    {
        // BuildHash is a deterministic SHA256 of all .cs files in the project (first 16 hex chars).
        // Generated by GenerateBuildHash in BetterFG.csproj into obj\...\BuildHash.g.cs.
        // Same source tree → same hash on any machine; source change → new hash.
#if EARLYACESSS || EARLYACCESS_XB1 || XB1
        public static bool IsPublicRelease => false;
#else
        public static bool IsPublicRelease => true;
#endif

        public static string Version => MyPluginInfo.PLUGIN_VERSION;

        public static string WatermarkLine1 => "Made by oreyre (oreytv)";
        // the "BettrFG" name is rendered as the logo image (see AddWatermarkLogoLine);
        // this is the rest of the line that follows it.
        public static string WatermarkLine2 => IsPublicRelease
            ? $"build {Version} [{BuildHash}]"
            : $"build {Version} [{BuildHash}], this build is not for public release";

        public static string WatermarkLine3 => IsPublicRelease ? "" : "Early access! woo!!!! boo!!! tooo!!";
    }
}
